### ISSUE TITLE
Changing hooks seems to have no effect

### ISSUE THREAD

**Issue by johannes-titz** [mgondan/mathml#1]
Really interesting package!

One question:

Regarding this example from the vignette:

```
hook(m_A, mean(X)["A"]) ; hook(s2_A, s["A"]^2L) ;
hook(n_A, n["A"])
hook(m_B, mean(X)["B"]) ; hook(s2_B, s["B"]^2L)
hook(n_B, n["B"]) ; hook(s2_p, s["pool"]^2L)
term <- quote(t <- dfrac(m_A - m_B, 
    sqrt(denote(s2_p, frac((n_A - 1L)*s2_A + (n_B - 1L)*s2_B, n_A + n_B - 2L),
                "the pooled variance.") * (frac(1L, n_A) + frac(1L, n_B)))))
math(term)
```

When running this code once and then trying to change the hooks, it does not seem to affect the result. I get the old expression. Restarting the session seems to be the only way to change the hooks. Am I doing something wrong or is this intended?

**Comment by mgondan** [comment]
I'll change that soon, you're completely right. I guess a new hook should just "overwrite" the old one.

**Comment by mgondan** [comment]
Ok, please try this:

````
remotes::install_github("mgondan/mathml")
library(mathml)
mathml(quote(a^2))
hook(a, aa)
mathml(quote(a^2))
unhook(a)
mathml(quote(a^2))
hook(a, aa)
mathml(quote(a^2))
````

**Comment by johannes-titz** [comment]
This solution functions, but I'm uncertain about its user-friendliness. To provide some background, I am developing exercises for a statistics course, and delivering feedback to students involves several iterations to refine the formula expressions. Frequently, it's a simple typo that needs correction after the initial version is created. I think it would be more user-friendly if the 'unhook' function is automatically invoked whenever 'hook' is called, if that is feasible and aligns with your perspective.

**Comment by mgondan** [comment]
I see. Please try this:
````
remotes::install_github("mgondan/mathml")
library(mathml)
mathml(quote(a^2))
hook(a, aa)
mathml(quote(a^2))
hook(a, aaa) # update/overwrite
mathml(quote(a^2))
unhook(a)
mathml(quote(a^2))
````

**Comment by johannes-titz** [comment]
Perfect, thank you!
