### ISSUE TITLE
How to import this package into other packages as developer

### ISSUE THREAD

**Issue by johannes-titz** [mgondan/mathml#2]
Is it possible to use this package inside other packages? It seems simply adding it as a dependency creates problems. If I do not call `library(mathml)`, it will just hang. Also calling `mathml::mathml` seems not to be possible. What happens when `library(mathml)` is called?

**Comment by mgondan** [comment]
I created a small demo package https://github.com/mgondan/onmathml, this is what I tried:
````
R> install.packages("mathml")
R> remotes::install_github("mgondan/onmathml")
> library(onmathml)
Lade nötiges Paket: mathml
Lade nötiges Paket: rolog
Found SWI-Prolog in the registry: C:\Program Files\swipl
Lade nötiges Paket: knitr
> hello()
[1] "<math><msup><mi>a</mi><mn>2.00</mn></msup></math>"
````
Do you see anything different? In fact, quite a few things happen when you "library(mathml)", i.e. R package rolog is loaded, and rolog searches for an installation of SWI-Prolog in different places (path, R package rswipl, Windows registry)

**Comment by johannes-titz** [comment]
Your responsiveness is truly impressive!

In the context of our setup differences, I've observed that you use "Depends" in the DESCRIPTION, whereas I've employed "Imports". Switching to "Depends" resolved the issue. This distinction is noteworthy, and it might be helpful to include a section in the vignette pointing this out. Consider:

> The main difference is that a package listed in Imports is only loaded when explicitly used, while a package listed in Depends is attached when your package is attached.
>
> Unless there is a good reason otherwise, you should always list packages in Imports, not Depends. That’s because a good package is self-contained and minimizes changes to the global landscape, including the search path.[6](https://r-pkgs.org/dependencies-mindset-background.html#fn6)

(From: [r-pkgs.org/description.html](https://r-pkgs.org/description.html))

In any case, the solution now works for me. I'm curious: Do you believe that using "Depends" is necessary due to the setup routine with Prolog?

**Comment by mgondan** [comment]
I added the respective note to the README and the vignette, thank you for pointing this out. I have no idea what the Imports/Depends stuff is about. As usual, the official description is not really helpful :-)
