### ISSUE TITLE
rounding issue

### ISSUE THREAD

**Issue by johannes-titz** [mgondan/mathml#9]
Is there a way to control rounding? A somewhat silly example:

```
mathml(0.023)
```

gives `<math><mn>0.02</mn></math>`

What controls the rounding?

**Comment by mgondan** [comment]
Short response

````
> mathml(call("pval", 0.023))
[1] "<math><mrow><mi>pval</mi><mo>&af;</mo><mrow><mo>(</mo><mn>0.02</mn><mo>)</mo></mrow></mrow></math>"
> mathml(quote(pval(0.023)))
[1] "<math><mrow><mi>pval</mi><mo>&af;</mo><mrow><mo>(</mo><mn>0.02</mn><mo>)</mo></mrow></mrow></math>"
````

**Comment by johannes-titz** [comment]
Flags makes sense, but this attribute is not documented in the help files; it just says that flags can be used. Which flags could be useful? Rounding is indeed very useful.

I do not get the first example, the output is 0.02 in both cases. I'll stick to the flags parameter, which feels more natural.

**Comment by mgondan** [comment]
> For some reason, `mathml(pi, flags=list(round=5L))` does not work. We will fix this.

This should now work in the current git, so that you can either type `mathml(pi, flags=list(round=5L))` or `mathml(pi, flags=list(quote(round(5L))))`. I think the former is more natural for R users. 

Please note that the flags set a default for rounding, that is, it applies for all floating point numbers of a given expression. I am a bit unsure if this is useful at all. In any case, more fine-tuning is available using `term <- call("round", 3.1415, 3L)`.

**Comment by johannes-titz** [comment]
Okay, interesting. Then `call` might be more useful. Thanks for the clarification. Maybe also something to add in the readme?

**Comment by mgondan** [comment]
More useful than what? quote? Yes, indeed. quote is mainly useful for trivial examples. In general, if you deal with non-standard evaluation, you need call(name, ...arguments...).

**Comment by johannes-titz** [comment]
More useful than flags. I guess rounding numbers off automatically is fine in many cases, but the user should know how to change this. When I call eval, I can round the final result afterwards. For me the rounding was unexpected behavior; the exact result seems a better default to me; but this will vary from user to user. I guess it also depends on the content, when you deal with very small numbers, rounding off to 2 digits is a nuisance. How about using options("digits") or some other general setting?

**Comment by mgondan** [comment]
The thing is: my students report average depression scores with 4 decimals 😅, as if that were a "measurement" at all, and as if it were precise in any way

**Comment by mgondan** [comment]
Now using getOption("digits") as the default.
